### ISSUE TITLE
Cannot run with node2.conf

### ISSUE THREAD

**Issue by Paul-Kim** [medibloc/go-medibloc#15]
Hi, I tried to run a node with conf/test/3nodes/node2.conf, but It didn't work with blew error message : 

```bash
@:~/go/src/github.com/medibloc/go-medibloc$ build/medi conf/test/3nodes/node2.conf 
panic: Invalid seed address config: err is invalid multiaddr, must begin with /, config value is conf/network/ed25519key.

goroutine 1 [running]:
github.com/medibloc/go-medibloc/net.NewP2PConfig(0xc0000c6a00, 0xc0000c6fc0)
        /home/mckim/go/src/github.com/medibloc/go-medibloc/net/config.go:111 +0x719
github.com/medibloc/go-medibloc/net.NewMedService(0xc0000c6a00, 0x1d, 0xc0000c6fc0, 0x0)
        /home/mckim/go/src/github.com/medibloc/go-medibloc/net/net_service.go:36 +0x45
github.com/medibloc/go-medibloc/medlet.New(0xc0000c6a00, 0x9, 0xc00022a50f, 0x5)
        /home/mckim/go/src/github.com/medibloc/go-medibloc/medlet/medlet.go:83 +0x2eb
main.medi(0xc0000dd340, 0x0, 0x0)
        /home/mckim/go/src/github.com/medibloc/go-medibloc/cmd/medi/main.go:63 +0x249
github.com/medibloc/go-medibloc/vendor/github.com/urfave/cli.HandleAction(0xba97c0, 0xe31cb8, 0xc0000dd340, 0x0, 0x0)
        /home/mckim/go/src/github.com/medibloc/go-medibloc/vendor/github.com/urfave/cli/app.go:490 +0xc8
github.com/medibloc/go-medibloc/vendor/github.com/urfave/cli.(*App).Run(0xc0000e16c0, 0xc0000c8000, 0x2, 0x2, 0x0, 0x0)
        /home/mckim/go/src/github.com/medibloc/go-medibloc/vendor/github.com/urfave/cli/app.go:264 +0x59d
main.main()
        /home/mckim/go/src/github.com/medibloc/go-medibloc/cmd/medi/main.go:42 +0xe4

```

Which information shold I fix?

**Comment by Paul-Kim** [comment]
I checked fix. Thanks.
>>>>> node2.conf
  seed: "conf/network/ed25519key" 
  private_key: "conf/network/ed25519key" 
<<<<<
